### ISSUE TITLE
Polling for new features in the Next Update

### ISSUE THREAD

**Issue by VandalByte** [VandalByte/darkmatter-grub2-theme#16]
Hey everyone
So I am thinking about doing a major new update for this theme ( redoing graphics, fonts etc.. )
But for few things I thought considering your opinions might be a good idea.

**Comment by vandalsoul** [comment]
**BOOT MENU**

Current boot menu is `solid black` so I was thinking of changing that.
React with the corresponding emoji

🚀 - **`change it to transparent`** *( might look something like in my [other theme](https://raw.githubusercontent.com/vandalsoul/dedsec-grub2-theme/main/media/previews/preview-compact.png) )*
😕 - **`remove the whole boot menu`** *( ie showing only the options and no boot menu )*
❤️ - **`keep it same`** *( making no changes )*

**Comment by vandalsoul** [comment]
**RIGHT-SIDE DISTRO LOGO**

In some of my *older* theme styles this logo is bigger than the height of it's boot menu but in the *new ones*, I did it so that it would fit in the same height or lower.
React with the corresponding emoji of which one you like

👎 - **previous [bigger one](https://raw.githubusercontent.com/vandalsoul/darkmatter-grub2-theme/main/media/previews/preview-popos.png)**
👍 - **new [small one](https://raw.githubusercontent.com/vandalsoul/darkmatter-grub2-theme/main/media/previews/preview-deepin.png)**

**Comment by vandalsoul** [comment]
If you have anything else you wanna share lemme know here...

**Comment by Jogai** [comment]
Maybe add it to the aur.

**Comment by vandalsoul** [comment]
@Jogai 
Umm idk since there's a lot of different theme styles idk how it's gonna end up 😅

**Comment by Jogai** [comment]
Much like this I guess: https://aur.archlinux.org/packages?K=grub-theme+2k-git

**Comment by Jogai** [comment]
No need to rush it. With the next update will be fine.

**Comment by linux-leo** [comment]
An unbranded version without any distro would be nice

**Comment by vandalsoul** [comment]
Hi @linux-leo 
Due to some personal priorities the update is getting delayed, but yeah I will add an unbranded version 👍🏼

**Comment by VandalByte** [comment]
Started working on Dark Matter update... :)
