### ISSUE TITLE
no icon for windows 10 ?

### ISSUE THREAD

**Issue by tethragon** [VandalByte/darkmatter-grub2-theme#34]
Hi and thanks for your great work.

When I was running linux mint 20.3 I had installed your darkmatter theme and worked flawlessly

Recently I wiped my nvme and installed linux mint 21. I installed (manually) again darkmatter theme and while it works, I noticed that there is no icon for windows 10. So when I boot (i have dual boot windows10/mint 21) there is no icon next to windows selection. I searched "icons" folder in darkmatter forlder and I noticed that there is only a "windows 11" icon. Could this be the problem?

**Comment by VandalByte** [comment]
Hi @tethragon 
The issue was that I forgot to include Windows 10 icons in the new version, and secondly, `windows11.png` must be renamed to `windows.png` in order to appear in the boot menu. I updated the naming and added Win 10 icons to the main [GitLab](https://gitlab.com/VandalByte/darkmatter-grub-theme) repo. So perhaps reinstall the new clone, or simply download the Win10 icons from the repo and rename them to `windows.png` 👍

**Comment by tethragon** [comment]
> Hi @tethragon The issue was that I forgot to include Windows 10 icons in the new version, and secondly, `windows11.png` must be renamed to `windows.png` in order to appear in the boot menu. I updated the naming and added Win 10 icons to the main [GitLab](https://gitlab.com/VandalByte/darkmatter-grub-theme) repo. So perhaps reinstall the new clone, or simply download the Win10 icons from the repo and rename them to `windows.png` +1

I just renamed a copy of windows11.png to windows.png. Problem solved. 

Now, is it possible to also have some icons for options "advanced options for linux mint" and option "uefi firmware" that also appear on my mint boot menu? Maybe a gear icon?

**Comment by VandalByte** [comment]
@tethragon 
Yeah it is possible, just check out my guide at [grub-tweaks](https://github.com/VandalByte/grub-tweaks#-adding-icons-for-submenus) repo. The icons for all that is already in the `icons` directory, so you don't need to add new ones
