### ISSUE TITLE
Debian Theme Blank Pop-up window

### ISSUE THREAD

**Issue by chris-fenning** [VandalByte/darkmatter-grub2-theme#41]
Just installed the Debian Theme and upon selecting the OS (Doesn't matter which one), a blank black pop-up window opens up on the screen and within 5 to 8 seconds the OS begins to load. Is there a solution to remove this pop-up window?

**Comment by VandalByte** [comment]
@chris-fenning 
Can you show a picture of the issue, I didn't quite get what you meant.

**Comment by chris-fenning** [comment]
![20240609_110054](https://github.com/VandalByte/darkmatter-grub2-theme/assets/172096297/c92b8663-8e2c-430d-8ed8-ee030c8048f5)
![20240609_105957](https://github.com/VandalByte/darkmatter-grub2-theme/assets/172096297/c9cfc025-84c5-4aa7-9b20-93a06b2f6efb)

**Comment by chris-fenning** [comment]
GRUB menu functions and selects everything perfectly fine, this window pops up before the OS loads. Interested in how to make the window go away.

**Comment by VandalByte** [comment]
So that's the console window that pops up usually when you select an option, shows the booting and all. I looked around and couldn't actually find a way to remove it, but if you want you can make it less awkward;

Try editing the theme.txt and remove all the `terminal-*` properties eg:
```
terminal-font: "Hack Bold 18"
terminal-left: "20%"
terminal-top: "35%"
terminal-width: "60%"
terminal-height: "40%"
terminal-box: "menu_bkg_*.png"
```
which should force it to be the default theme that is just full screen black console.

It won't be showing much booting sequence cause in most distros the `grub` file will have a property
```
GRUB_CMDLINE_LINUX_DEFAULT="splash quiet"

change it to this 

GRUB_CMDLINE_LINUX_DEFAULT="splash"
```
Don't forget to update grub file afterwards.

Console window also pops up when you click **C** while on the boot menu, to go back type `normal` and press Enter

That's all I have, if you do find some other solution do let me know.

**Comment by chris-fenning** [comment]
Thank you for the help, that did not change much really; however, you helped me come to a far better conclusion. Instead of having a smaller window pop up on the screen for a few seconds, I would prefer to have the screen go completely blank for a few seconds then load to the selected OS. So I simply modified the theme.txt to:

terminal-font: "Hack Bold 18"
terminal-left: "100%"
terminal-top: "100%"
terminal-width: "100%"
terminal-height: "100%"
terminal-box: "menu_bkg_*.png"

This looks so much better and far more natural than before. I tried to removing the quiet splash but found that reducing my GRUB Timeout from 10 seconds to 8 seconds, also reduces the  terminal window display time as well... so I kept it on "quiet" and kept the blank screen for the screen load.  

Absolutely Love This Theme!!!
Thanks Again!!!
